deps:
  run:
    - curl -fL https://github.com/harness/harness-cli/releases/latest/download/harness-cli-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
run:
  binary:
    source: https://github.com/harness/drone-har/releases/download/{{ release }}/plugin-{{ os }}-{{ arch }}.zst
